---
- name: instala o docker
  ansible.builtin.import_tasks: install_docker.yml
  tags:
    - docker

- name: instala o Prometheus e o Alertmanager
  ansible.builtin.import_tasks: setup_prom_alert.yml
  tags:
    - PromAlert

- name: verifica se esta tudo OK
  ansible.builtin.import_tasks: verify.yml
  tags:
    - verify
